### ISSUE TITLE
NullPointerException when cooking a dough in a stone oven on a forge

### ISSUE THREAD

**Issue by jcaballo** [TeamMFR/MineFantasy-reborn#22]
When trying to cook a dough in my stone oven on a forge, the server crash with this error :
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
Caused by: java.lang.NullPointerException
	at minefantasy.mfr.tile.TileEntityRoast.func_73660_a(TileEntityRoast.java:77) ~[TileEntityRoast.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1838) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 mor
[2022-02-08-2.log](https://github.com/TeamMFR/MineFantasyReforged/files/8026329/2022-02-08-2.log)

**Comment by ThatPolishKid99** [comment]
Can I please get the full crash report file

**Comment by jcaballo** [comment]
Yes it here : https://github.com/TeamMFR/MineFantasyReforged/files/8026329/2022-02-08-2.log

**Comment by jcaballo** [comment]
Ah yes sorry it was the wrong file : [crash-reports_crash-2022-02-08_17.54.19-server (1).txt](https://github.com/TeamMFR/MineFantasyReforged/files/8027108/crash-reports_crash-2022-02-08_17.54.19-server.1.txt)
