### ISSUE TITLE
Recipes missing and crash while trying to right click with pickaxe on ore blocks

### ISSUE THREAD

**Issue by DangerNuzzles** [TeamMFR/MineFantasy-reborn#33]
The smelting recipes for both the clay jug and the ingot mold are missing. Had to add them manually via crafttweaker.

This happens when I right click certain harvestable ores. Perhaps because I am using just enough ids? I have a lot of mods.

Time: 2022-02-28 17:23:27 PST
Description: Unexpected error

java.lang.NullPointerException
    at minefantasy.mfr.item.ItemPickMFR.onItemRightClick(ItemPickMFR.java:81)
    at net.minecraft.item.ItemStack.useItemRightClick(ItemStack.java:217)
    at net.minecraft.client.multiplayer.PlayerControllerMP.processRightClick(PlayerControllerMP.java:511)
    at net.minecraft.client.Minecraft.rightClickMouse(Minecraft.java:1597)
    at net.minecraft.client.Minecraft.processKeyBinds(Minecraft.java:2254)
    at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:2020)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1808)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by ThatPolishKid99** [comment]
Please make sure you're on the latest version, as I have been unable to replicate your issue with the ingot mold and the clay jugs. As for the pickaxe crash, I am aware, it is fixed in dev and will be apart of the next update. I have edited the title of the relevant issue to avoid duplication, and will close this one. Feel free to open a new one that is explicitly about the smelting issue, if it persists.

**Comment by DangerNuzzles** [comment]
Whops! I realized that they are MF stove recipes. Maybe add JEI support for these?
